### ISSUE TITLE
TOB-PINT-11 -  Static extrinsic weight

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#368] opened 2021-09-13 20:00 UTC
Remove static weights.

**Comment by clearloop** [comment] 2021-09-14 13:13
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/368?planning-poker) with ZenHub @mattsse

**Comment by mattsse** [comment] 2021-09-15 13:24
this is a dupe of #261 closing in favor of that one

**Closed by mattsse** 2021-09-15 13:24 UTC
Labels: blocked
