### ISSUE TITLE
Elevate priority of important operations

### ISSUE THREAD

**Issue by Redoudou** [ChainSafe/PINT#375] opened 2021-09-14 00:15 UTC
Make extrinsincs related to governance either `DispatchClass::Mandatory` if possible or `Operational`

**Comment by mattsse** [comment] 2021-09-14 10:43
This is essentially a dupe of #373

**Comment by clearloop** [comment] 2021-09-14 13:25
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/375?planning-poker) with ZenHub @mattsse

**Comment by clearloop** [comment] 2021-09-14 13:26
can add more logic on the checking of the weight to optimize this

**Closed** 2021-09-17 11:38 UTC
Labels: p2, discussion
